In [1]:
fkdjgfgfgnfdkg

NameError: name 'fkdjgfgfgnfdkg' is not defined

In [2]:
#fgjkfngfdngfngkfdngfdngfdngksfdn

## Basic Python

In [3]:
a=56

In [4]:
a

56

In [5]:
type(a)

int

In [6]:
2b=89

SyntaxError: invalid syntax (Temp/ipykernel_19464/2573077915.py, line 1)

In [7]:
@b=78

SyntaxError: invalid syntax (Temp/ipykernel_19464/3545519428.py, line 1)

In [8]:
name_of_var=45

In [9]:
name_of_var

45

In [10]:
x=44

In [16]:
y=90

In [12]:
x

44

In [13]:
y

33

In [14]:
z=x+y

In [15]:
z

77

In [17]:
z=x+y

In [18]:
z

134

## data types

In [19]:
a=56

In [20]:
type(a)

int

In [21]:
b=78.90

In [22]:
type(b)

float

In [23]:
s='hello'

In [24]:
s

'hello'

In [25]:
type(s)

str

In [26]:
name="Rohit"

In [27]:
type(name)

str

In [28]:
name

'Rohit'

In [29]:
d=True

In [30]:
type(d)

bool

In [31]:
e=False

In [32]:
e

False

In [33]:
type(e)

bool

In [34]:
True+False

1

In [35]:
True+False+True+True+True+False

4

In [36]:
True+False+True+True+True+False+5

9

In [37]:
c=5j+8

In [38]:
c

(8+5j)

In [39]:
type(c)

complex

### String Indexing

In [41]:
s='hello'

In [42]:
type(s)

str

In [43]:
s

'hello'

In [44]:
s[1]

'e'

In [45]:
s[0]

'h'

In [46]:
s='abcdefghijk'

In [47]:
type(s)

str

In [48]:
s

'abcdefghijk'

In [49]:
s[3]

'd'

In [50]:
s[12]

IndexError: string index out of range

In [51]:
s[:]

'abcdefghijk'

In [52]:
s[0:]

'abcdefghijk'

In [53]:
s[0:11]

'abcdefghijk'

In [54]:
s[0:6]

'abcdef'

In [55]:
s[5:8]

'fgh'

In [56]:
s[8:11]

'ijk'

In [57]:
s[100]

IndexError: string index out of range

In [58]:
s[100:]

''

In [59]:
s[:12]

'abcdefghijk'

In [60]:
s[:6]

'abcdef'

In [61]:
s[45:90]

''

In [62]:
s[2:12:2]

'cegik'

In [63]:
s[2:8:2]

'ceg'

In [64]:
s[3:9:3]

'dg'

In [65]:
s

'abcdefghijk'

In [66]:
s[-2]

'j'

In [67]:
s[-8]

'd'

In [68]:
s[-2:-8]

''

In [69]:
s[-5:-11:-2]

'gec'

In [70]:
s

'abcdefghijk'

In [71]:
s[::-1]

'kjihgfedcba'

In [72]:
'indiA'[::-1]

'Aidni'

In [73]:
65564654[::-1]

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\Admin\AppData\Local\Temp/ipykernel_19464/2779207680.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  65564654[::-1]


TypeError: 'int' object is not subscriptable

In [74]:
'65564654'[::-1]

'45646556'

In [75]:
pwd

'C:\\Users\\Admin'

In [ ]:
s[:-1]='abcdefghij'

In [76]:
s[::-1]

'kjihgfedcba'

In [77]:
s

'abcdefghijk'

In [78]:
s[:-1]

'abcdefghij'

In [79]:
a=89
b="rohit"

In [80]:
a

89

In [81]:
b

'rohit'

In [82]:
'my number is {} and my name is {}'.format(a,b)

'my number is 89 and my name is rohit'

In [83]:
'my number is {} and my name is {}'.format(b,a)

'my number is rohit and my name is 89'

In [84]:
'my number is {one} and my name is {two}'.format(one=a,two=b)

'my number is 89 and my name is rohit'

In [85]:
'my number is {one} and my name is {two} {two} {two}'.format(one=a,two=b)

'my number is 89 and my name is rohit rohit rohit'

In [86]:
## Lists 

In [87]:
[44,88,90,34]

[44, 88, 90, 34]

In [88]:
type([44,88,90,34])

list

In [89]:
a=[12,89,34,56,78,23,55]

In [90]:
a

[12, 89, 34, 56, 78, 23, 55]

In [91]:
type(a)

list

In [92]:
a.append(456)

In [93]:
a

[12, 89, 34, 56, 78, 23, 55, 456]

In [94]:
b=[56,88,'hello','bye','python',78,99]

In [95]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [96]:
type(b)

list

In [97]:
c=[67,89,'morning',[11,12,13,67,'evening',78],5555,333,'bye']

In [98]:
c

[67, 89, 'morning', [11, 12, 13, 67, 'evening', 78], 5555, 333, 'bye']

In [99]:
type(c)

list

In [100]:
a

[12, 89, 34, 56, 78, 23, 55, 456]

In [101]:
a[4]

78

In [102]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [103]:
b[3]

'bye'

In [104]:
b[3][1]

'y'

In [105]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [106]:
b[:]

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [107]:
b[0:12:2]

[56, 'hello', 'python', 99]

In [108]:
b[0:12:3]

[56, 'bye', 99]

In [109]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [110]:
b[4]

'python'

In [111]:
b[:]

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [112]:
b[0:10]

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [113]:
b[0:10:2]

[56, 'hello', 'python', 99]

In [114]:
b[0:10:3]

[56, 'bye', 99]

In [115]:
yogeshwar_list=[56, 88, 'hello', 'bye', 'python', 78, 99]

In [116]:
yogeshwar_list

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [119]:
yogeshwar_list[3][4]

IndexError: string index out of range

In [120]:
yogeshwar_list[3]

'bye'

In [121]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [122]:
f=[10,44,67,'hello',[33,67,'bye',[55,66,'SUNDAY','holiday',88]]]

In [123]:
f

[10, 44, 67, 'hello', [33, 67, 'bye', [55, 66, 'SUNDAY', 'holiday', 88]]]

In [124]:
type(f)

list

In [125]:
f[4][3][2]

'SUNDAY'

In [126]:
f[4][2]

'bye'

In [127]:
f

[10, 44, 67, 'hello', [33, 67, 'bye', [55, 66, 'SUNDAY', 'holiday', 88]]]

In [128]:
f[4]

[33, 67, 'bye', [55, 66, 'SUNDAY', 'holiday', 88]]

In [129]:
f[4][3]

[55, 66, 'SUNDAY', 'holiday', 88]

In [130]:
f[4][3][2]

'SUNDAY'

In [131]:
type(f[4][3][2])

str

In [132]:
f[4][3][2][3:]

'DAY'

In [133]:
a

[12, 89, 34, 56, 78, 23, 55, 456]

In [134]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [135]:
c

[67, 89, 'morning', [11, 12, 13, 67, 'evening', 78], 5555, 333, 'bye']

In [138]:
f

[10, 44, 67, 'hello', [33, 67, 'bye', [55, 66, 'SUNDAY', 'holiday', 88]]]

In [139]:
a.clear()

In [140]:
a

[]

In [141]:
b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [142]:
copy_of_b=b.copy()

In [143]:
copy_of_b

[56, 88, 'hello', 'bye', 'python', 78, 99]

In [144]:
b.count(88)

1

In [145]:
b.reverse()

In [146]:
b

[99, 78, 'python', 'bye', 'hello', 88, 56]

In [147]:
b.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

In [148]:
a=[55,2,4,99,45,78,12131]

In [149]:
a

[55, 2, 4, 99, 45, 78, 12131]

In [150]:
a.sort()

In [151]:
a

[2, 4, 45, 55, 78, 99, 12131]

In [152]:
a.sort(reverse=True)

In [153]:
a

[12131, 99, 78, 55, 45, 4, 2]

In [154]:
a

[12131, 99, 78, 55, 45, 4, 2]

In [155]:
a.count(99)

1

In [156]:
a=[45,89,33,45,66,45,2,3,45]

In [157]:
a

[45, 89, 33, 45, 66, 45, 2, 3, 45]

In [158]:
a.count(45)

4

In [159]:
b

[99, 78, 'python', 'bye', 'hello', 88, 56]

In [160]:
b.index('bye')

3

### Dictionaris

In [161]:
d1={'name':'rohit'}

In [162]:
type(d1)

dict

In [163]:
d1

{'name': 'rohit'}

In [164]:
d2={"student_name":"Mohit","class":10,'marks':55,'City':'Pune'}

In [165]:
d2

{'student_name': 'Mohit', 'class': 10, 'marks': 55, 'City': 'Pune'}

In [166]:
type(d2)

dict

In [167]:
d2['marks']

55

In [168]:
d3={'player':'sachin','teams':['India','All Stars','YK','MI'],
    'Location':'Mumbai','State':'Maharashtra','runs':500000}

In [169]:
d3

{'player': 'sachin',
 'teams': ['India', 'All Stars', 'YK', 'MI'],
 'Location': 'Mumbai',
 'State': 'Maharashtra',
 'runs': 500000}

In [170]:
type(d3)

dict

In [171]:
d3['State']

'Maharashtra'

In [172]:
d3['runs']

500000

In [173]:
d3['teams']

['India', 'All Stars', 'YK', 'MI']

In [175]:
d3['teams'][1]

'All Stars'

In [176]:
d3

{'player': 'sachin',
 'teams': ['India', 'All Stars', 'YK', 'MI'],
 'Location': 'Mumbai',
 'State': 'Maharashtra',
 'runs': 500000}

In [177]:
d4={'marks':78,'key1':{'key2':[34,78,99,1234]}}

In [178]:
d4

{'marks': 78, 'key1': {'key2': [34, 78, 99, 1234]}}

In [179]:
d4['key1']

{'key2': [34, 78, 99, 1234]}

In [180]:
d4['key1']['key2']

[34, 78, 99, 1234]

In [181]:
d4['key1']['key2'][2]

99

In [182]:
d1

{'name': 'rohit'}

In [183]:
d2

{'student_name': 'Mohit', 'class': 10, 'marks': 55, 'City': 'Pune'}

In [184]:
d3

{'player': 'sachin',
 'teams': ['India', 'All Stars', 'YK', 'MI'],
 'Location': 'Mumbai',
 'State': 'Maharashtra',
 'runs': 500000}

In [185]:
d4

{'marks': 78, 'key1': {'key2': [34, 78, 99, 1234]}}

In [187]:
d3.keys()

dict_keys(['player', 'teams', 'Location', 'State', 'runs'])

In [188]:
d3.values()

dict_values(['sachin', ['India', 'All Stars', 'YK', 'MI'], 'Mumbai', 'Maharashtra', 500000])

In [189]:
d3.items()

dict_items([('player', 'sachin'), ('teams', ['India', 'All Stars', 'YK', 'MI']), ('Location', 'Mumbai'), ('State', 'Maharashtra'), ('runs', 500000)])

In [190]:
d3.pop()

TypeError: pop expected at least 1 argument, got 0

In [191]:
d2

{'student_name': 'Mohit', 'class': 10, 'marks': 55, 'City': 'Pune'}

In [192]:
d2.pop('marks')

55

In [193]:
d2

{'student_name': 'Mohit', 'class': 10, 'City': 'Pune'}

In [194]:
d2.popitem()

('City', 'Pune')

In [195]:
d2

{'student_name': 'Mohit', 'class': 10}

In [196]:
## tuples

In [197]:
my_tuple1=(45,78,99,22,56)

In [198]:
my_tuple1

(45, 78, 99, 22, 56)

In [199]:
type(my_tuple1)

tuple

In [200]:
my_tuple2=(45,78,'hello','bye',78788)

In [201]:
my_tuple2

(45, 78, 'hello', 'bye', 78788)

In [202]:
type(my_tuple1)

tuple

In [203]:
my_tuple2.count(78)

1

In [204]:
my_tuple2.index(78)

1

In [205]:
my_tuple1

(45, 78, 99, 22, 56)

In [206]:
my_tuple2

(45, 78, 'hello', 'bye', 78788)

In [207]:
a

[45, 89, 33, 45, 66, 45, 2, 3, 45]

In [208]:
a[3]

45

In [209]:
a[3]=88098

In [210]:
a

[45, 89, 33, 88098, 66, 45, 2, 3, 45]

In [211]:
my_tuple1

(45, 78, 99, 22, 56)

In [212]:
my_tuple1[3]

22

In [213]:
my_tuple1[3]=78786

TypeError: 'tuple' object does not support item assignment

## Sets -----> collection of unique elements

In [216]:
my_set1={1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3}

In [217]:
my_set1

{1, 2, 3}

In [218]:
type(my_set1)

set

In [219]:
my_set2={}

In [223]:
my_set2

{}

In [220]:
type(my_set2)

dict

In [221]:
my_set3=set()

In [222]:
my_set3

set()

In [224]:
my_set1

{1, 2, 3}

In [225]:
my_set1.add(78)

In [226]:
my_set1

{1, 2, 3, 78}

In [227]:
my_set1.add(78,45)

TypeError: set.add() takes exactly one argument (2 given)

In [228]:
add_set={78,45}

In [229]:
result=my_set1.union(add_set)

In [230]:
result

{1, 2, 3, 45, 78}

In [1]:
## Revision session2

In [2]:
s={3,7,8,3,5,8,8,8,8,8,3,7}

In [3]:
s

{3, 5, 7, 8}

In [4]:
type(s)

set

In [5]:
s.add(89)

In [6]:
s

{3, 5, 7, 8, 89}

In [7]:
s.add(4)

In [8]:
s

{3, 4, 5, 7, 8, 89}

In [9]:
s.add(5)

In [10]:
s

{3, 4, 5, 7, 8, 89}

In [11]:
s.add(78,99)

TypeError: set.add() takes exactly one argument (2 given)

In [12]:
s

{3, 4, 5, 7, 8, 89}

In [13]:
s2={78,99}

In [14]:
s_new=s.union(s2)

In [15]:
s_new

{3, 4, 5, 7, 8, 78, 89, 99}

In [16]:
s

{3, 4, 5, 7, 8, 89}

In [17]:
type(s)

set

In [18]:
my_list1=[3,4,5]

In [19]:
type(my_list1)

list

In [20]:
y=(3,4,5)

In [21]:
type(y)

tuple

In [22]:
d={'number':8,'marks':90}

In [23]:
type(d)

dict

In [24]:
### Comparision Operators

In [25]:
4>9

False

In [26]:
5<90

True

In [27]:
6>=3

True

In [28]:
78<=45

False

In [29]:
2=7

SyntaxError: cannot assign to literal (Temp/ipykernel_12092/2705102720.py, line 1)

In [30]:
2==7

False

In [31]:
4==4

True

In [32]:
'Sachin'=='sachin'

False

In [33]:
'sachin'=='sachin'

True

In [34]:
'hi'=='bye'

False

In [35]:
5!=8

True

In [36]:
5!=5

False

In [37]:
35+40

75

In [38]:
'35'+'40'

'3540'

In [39]:
'35'+40

TypeError: can only concatenate str (not "int") to str

In [40]:
'35'*3

'353535'

In [41]:
'35'-'22'

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [42]:
'35'-32

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [43]:
4>5 and 6<9

False

In [44]:
4>5 or 6<9

True

In [45]:
4>5 and 6<9 or 5==3

False

In [46]:
4>5 or 6<9 and 5==3

False

In [47]:
### if else elif

In [48]:
if 3<8:
    print("Hello Everyone")

Hello Everyone


In [49]:
if 3>8:
    print("Hello evryone")

In [52]:
if 5==5:
    x=7+99
    print(x)

106


In [51]:
x

106

In [53]:
if True:
    print("hi")

hi


In [1]:
if False:
print("hi")

IndentationError: expected an indented block (Temp/ipykernel_5296/3859472395.py, line 2)

In [2]:
if 5<9:
    print("hi")

hi


In [3]:
if 5>9:
    print("first")
else:
    print("Last")

Last


In [4]:
if 5>9:
    x=8*8
else:
    x=8+8

In [5]:
x

16

In [6]:
if 5>9:
    print("first")
elif 5==5:
    print("Second")
else:
    print("Last")

Second


In [7]:
if 5>9:
    print("first")
elif 5==9:
    print("Second")
else:
    print("Last")

Last


In [8]:
if 5>9:
    print("first")
elif 5==9:
    print("Second")
elif 8==8:
    print("Third")
else:
    print("Last")

Third


In [9]:
if 5>9:
    print("first")
elif 5==9:
    print("Second")
elif 8==8:
    print("Third")
elif 9==9:
    print("Fourth")
else:
    print("Last")

Third


In [10]:
if 6>9:
    x=2*2
else:
    x=2+2

In [11]:
x

4

In [12]:
### for Loop

In [13]:
data=[10,20,30,40,50]

In [14]:
data

[10, 20, 30, 40, 50]

In [15]:
type(data)

list

In [16]:
for v in data:
    print(v)

10
20
30
40
50


In [17]:
for v in data:
    print(v,end=' ')

10 20 30 40 50 

In [18]:
for v in data:
    print(v,end='     ')

10     20     30     40     50     

In [19]:
for v in data:
    print(v,end='*')

10*20*30*40*50*

In [20]:
data

[10, 20, 30, 40, 50]

In [21]:
for v in data[::-1]:
    print(v)

50
40
30
20
10


In [22]:
for v in data[2:4]:
    print(v)

30
40


In [25]:
for v in data:
    print(v+v)

20
40
60
80
100


In [26]:
for i in data:
    print('Python')

Python
Python
Python
Python
Python


In [27]:
### while loop

In [28]:
i=8
while i<20:
    print(i)
    i=i+1

8
9
10
11
12
13
14
15
16
17
18
19


In [30]:
i=8
while i<20:
    print(i)
    i+=1

8
9
10
11
12
13
14
15
16
17
18
19


In [31]:
### range()----a generator function 

In [32]:
range(10)

range(0, 10)

In [33]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [36]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [37]:
list(range(10,20,2))

[10, 12, 14, 16, 18]

In [38]:
list(range(10,25,5))

[10, 15, 20]

In [40]:
list(range(10,20,2))

[10, 12, 14, 16, 18]

In [41]:
list(range(-10,10,3))

[-10, -7, -4, -1, 2, 5, 8]

In [43]:
for v in range(7):
    print(v)

0
1
2
3
4
5
6


In [44]:
for v in range(7):
    print(v,end=' ')

0 1 2 3 4 5 6 

In [45]:
for v in range(1000):
    print(v,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 27

In [47]:
for v in range(15,50,5):
    print('Python')

Python
Python
Python
Python
Python
Python
Python


In [48]:
for v in range(15,50,5):
    print('Python',end=' ')

Python Python Python Python Python Python Python 

In [49]:
for v in range(15,50,5):
    print('*',end=' ')

* * * * * * * 

In [51]:
for v in range(15,50,5):
    print('*')
    print('*',end=' ')
    print('*',end=' ')    

*
* * *
* * *
* * *
* * *
* * *
* * *
* * 

In [52]:
## List Comprehension

In [53]:
data

[10, 20, 30, 40, 50]

In [54]:
data_square=[]
for v in data:
    data_square.append(v**2)
print(data_square)

[100, 400, 900, 1600, 2500]


In [55]:
square_data=[v**2 for v in data]

In [56]:
square_data

[100, 400, 900, 1600, 2500]

In [57]:
'45'+67

TypeError: can only concatenate str (not "int") to str

In [58]:
int('45')+67

112

In [59]:
'45'+str(67)

'4567'

In [60]:
bool(0)

False

In [61]:
bool(1)

True

In [62]:
bool(9)

True

In [63]:
bool(10)

True

In [64]:
bool(-5)

True

In [65]:
bool(0)

False

In [66]:
bool([])

False

In [67]:
bool(())

False

In [68]:
bool({})

False

In [69]:
bool(set())

False

In [70]:
bool([8])

True

In [1]:
## Revision 3

In [2]:
bool({})

False

In [3]:
bool(True)

True

In [4]:
bool([False])

True

In [5]:
bool([])

False

In [6]:
bool('')

False

## Functions

In [7]:
def my_fun1():
    print("Hello Everyone")

In [8]:
my_fun1

<function __main__.my_fun1()>

In [9]:
my_fun1()

Hello Everyone


In [10]:
def find_square(n):
    return n*n

In [11]:
find_square()

TypeError: find_square() missing 1 required positional argument: 'n'

In [12]:
find_square(8)

64

In [17]:
def my_fun2(name):
    print("Hi Mr. "+name)

In [14]:
my_fun2()

TypeError: my_fun2() missing 1 required positional argument: 'name'

In [18]:
my_fun2('Rohit')

Hi Mr. Rohit


In [19]:
def my_fun3(name="Rahul"):
    print("Hello "+name)

In [20]:
my_fun3("Mohit")

Hello Mohit


In [21]:
my_fun3()

Hello Rahul


In [24]:
def add_2nos(a,b):
    '''
    This function adds two numbers
    provide 2 arguments
    
    note:This is written by Mr. Yogesh Murumkar
    
    '''
    return a+b

In [25]:
add_2nos(6,7)

13

In [26]:
add_2nos(8,9)

17

In [27]:
def fun1(n):
    return n**3

In [31]:
def fun2(m):
    print(m**3)

In [33]:
type(fun1(3))

int

In [34]:
type(fun2(3))

27


NoneType

In [36]:
### Lambda Expressions---->an anonymous function

In [37]:
def find_square(n):
    return n*n

In [38]:
find_square(9)

81

In [39]:
lam1=lambda v:v*v

In [40]:
lam1

<function __main__.<lambda>(v)>

In [41]:
lam1(8)

64

In [42]:
## map and filter

In [43]:
data=[10,20,30,40,50]

In [44]:
data

[10, 20, 30, 40, 50]

In [45]:
map(find_square,data)

In [46]:
list(map(find_square,data))

[100, 400, 900, 1600, 2500]

In [47]:
list(map(lambda v:v*v*v,data))

[1000, 8000, 27000, 64000, 125000]

In [48]:
l1=lambda x:x*x*x

In [49]:
list(map(l1,data))

[1000, 8000, 27000, 64000, 125000]

In [50]:
data

[10, 20, 30, 40, 50]

In [52]:
list(map(lambda v:v%2==0,data))

[True, True, True, True, True]

In [53]:
data=[11,12,13,14,15,16]

In [54]:
list(map(lambda v:v%2==0,data))

[False, True, False, True, False, True]

In [55]:
list(filter(lambda v:v%2==0,data))

[12, 14, 16]

In [56]:
fruits=['mango','banana','apple','orange']

In [57]:
fruits

['mango', 'banana', 'apple', 'orange']

In [59]:
l2=lambda v:v[1]=='a'

In [60]:
list(filter(l2,fruits))

['mango', 'banana']

In [61]:
### Methods

In [62]:
s="we are learning, Python! and it, requires! practice"

In [63]:
s

'we are learning, Python! and it, requires! practice'

In [64]:
s.upper()

'WE ARE LEARNING, PYTHON! AND IT, REQUIRES! PRACTICE'

In [65]:
s.lower()

'we are learning, python! and it, requires! practice'

In [66]:
s.title()

'We Are Learning, Python! And It, Requires! Practice'

In [67]:
s.capitalize()

'We are learning, python! and it, requires! practice'

In [68]:
s.split()

['we', 'are', 'learning,', 'Python!', 'and', 'it,', 'requires!', 'practice']

In [69]:
s.split()[3]

'Python!'

In [70]:
s

'we are learning, Python! and it, requires! practice'

In [71]:
s.split(',')

['we are learning', ' Python! and it', ' requires! practice']

In [72]:
s.split('!')

['we are learning, Python', ' and it, requires', ' practice']

In [73]:
s

'we are learning, Python! and it, requires! practice'

In [74]:
s.split('P')

['we are learning, ', 'ython! and it, requires! practice']

In [75]:
s.split('we are learning, Python! and it, requires! practice')

['', '']

In [76]:
data=[(1,2),(3,4),(5,6)]

In [77]:
data

[(1, 2), (3, 4), (5, 6)]

In [78]:
data[0]

(1, 2)

In [79]:
data[0][0]

1

In [80]:
data[0][1]

2

In [81]:
data

[(1, 2), (3, 4), (5, 6)]

In [83]:
data[2][0]

5

In [84]:
for v in data:
    print(v)

(1, 2)
(3, 4)
(5, 6)


In [85]:
data

[(1, 2), (3, 4), (5, 6)]

In [86]:
for v in data:
    print(v[0])

1
3
5


In [87]:
for v in data:
    print(v[1])

2
4
6


In [88]:
for v in data:
    print(v[0])
    print(v[1])

1
2
3
4
5
6


In [89]:
for a,b in data:
    print(a)

1
3
5


In [90]:
for a,b in data:
    print(b)

2
4
6


In [91]:
for a,b in data:
    print(a)
    print(b)

1
2
3
4
5
6


In [92]:
data

[(1, 2), (3, 4), (5, 6)]

In [93]:
n1=input("Enter the Number: ")

Enter the Number: 45


In [94]:
n1

'45'

In [95]:
type(n1)

str

In [96]:
n=5467

In [97]:
n

5467

In [98]:
name='sachin'

In [99]:
name[::-1]

'nihcas'

In [100]:
n

5467

In [102]:
int(str(n)[::-1])

7645

In [103]:
a='rohit'
b=78

In [104]:
'my name is {} and my number is {}'.format(a,b)

'my name is rohit and my number is 78'

In [105]:
'my name is {} and my number is {}'.format(b,a)

'my name is 78 and my number is rohit'

In [106]:
'my name is {} and my number is {} {} {}'.format(a,b,a,a)

'my name is rohit and my number is 78 rohit rohit'

In [107]:
'my name is {one} and my number is {two} {one} {one} {one}'.format(one=a,two=b)

'my name is rohit and my number is 78 rohit rohit rohit'

## Revision Session4

In [1]:
num1=input("Enter the number:")

Enter the number:56


In [2]:
type(num1)

str

In [3]:
num1

'56'

In [4]:
'67'+'78'

'6778'

In [12]:
'hello'[::-1]

'olleh'

In [13]:
'789'[::-1]

'987'

In [14]:
789[::-1]

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\Admin\AppData\Local\Temp/ipykernel_8644/2188738136.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  789[::-1]


TypeError: 'int' object is not subscriptable

In [15]:
num1=input("Enter the number:")
num2=int(num1[::-1])
num3=int(num1)+num2

Enter the number:78


In [16]:
num1

'78'

In [17]:
num2

87

In [18]:
num3

165

### numpy package

In [19]:
!pip install numpy

In [20]:
import numpy

In [21]:
import numpy as np

In [22]:
## Numpy arrays

In [23]:
my_list1=[5,6,7,8,9]

In [24]:
my_list1

[5, 6, 7, 8, 9]

In [25]:
type(my_list1)

list

In [26]:
arr1=np.array(my_list1)

In [27]:
arr1

array([5, 6, 7, 8, 9])

In [28]:
my_list2=[[10,20,30],[45,67,89],[1,2,3]]

In [29]:
my_list2

[[10, 20, 30], [45, 67, 89], [1, 2, 3]]

In [30]:
type(my_list2)

list

In [32]:
arr2=np.array(my_list2)

In [33]:
arr2

array([[10, 20, 30],
       [45, 67, 89],
       [ 1,  2,  3]])

In [34]:
type(arr2)

numpy.ndarray

In [35]:
type(arr1)

numpy.ndarray

In [36]:
### built in methods in numpy

In [37]:
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [38]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [46]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [47]:
np.zeros(10)+89

array([89., 89., 89., 89., 89., 89., 89., 89., 89., 89.])

In [49]:
np.ones(10)*88

array([88., 88., 88., 88., 88., 88., 88., 88., 88., 88.])

In [50]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [52]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
np.linspace(10,50,100)

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

In [56]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
np.random.rand()

0.6070726322139607

In [58]:
np.random.rand()

0.6851099463689897

In [59]:
np.random.rand()

0.018147883199952752

In [60]:
np.random.rand(7)

array([0.88786334, 0.96143245, 0.23147106, 0.24763167, 0.23685688,
       0.24269361, 0.42694457])

In [61]:
np.random.rand(7)

array([0.31031161, 0.87475538, 0.58215343, 0.03214747, 0.25990458,
       0.58870112, 0.14587093])

In [63]:
np.random.rand(20)

array([0.5719842 , 0.06602395, 0.98503161, 0.60609785, 0.98177692,
       0.31433818, 0.80539723, 0.72980741, 0.50369572, 0.5118989 ,
       0.92193194, 0.76542165, 0.05309034, 0.40470223, 0.05755787,
       0.78890208, 0.05086095, 0.6595452 , 0.67317547, 0.25893617])

In [64]:
np.random.randn()

-0.06332540928769709

In [65]:
np.random.randn()

0.3653997311669427

In [66]:
np.random.randn()

-0.05911380664404305

In [67]:
np.random.randn(5)

array([ 0.96169468,  0.23647198, -1.11563751, -0.10164985, -1.70497775])

In [68]:
np.random.randn(12)

array([ 1.12072453,  1.24497643,  1.14826619,  0.85782756,  0.84559216,
       -0.01121672,  1.46864646, -1.99045688,  0.99647633, -0.40790464,
        0.90648274, -0.64262439])

In [69]:
np.random.randn(5,5)

array([[-0.47595313,  0.30686624, -0.89945234, -0.66924185,  0.09590686],
       [ 0.40597438, -0.87021312,  1.55611717, -0.20592925, -0.44044812],
       [ 0.18377829, -1.07462559,  0.57694697,  1.31835677, -1.21271628],
       [-0.27334815,  0.41408612, -0.02975763, -2.42144296,  0.93573258],
       [ 0.0411018 , -1.67425108, -0.19200183,  0.42593169, -0.23061224]])

In [70]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [71]:
np.random.randint(8)

1

In [72]:
np.random.randint(8)

1

In [73]:
np.random.randint(8)

7

In [74]:
np.random.randint(8)

1

In [75]:
np.random.randint(8)

5

In [80]:
np.random.randint(5,15)

12

In [81]:
np.random.randint(5,15,3)

array([ 9, 13, 12])

In [82]:
np.random.randint(5,15,3)

array([9, 8, 5])

In [83]:
np.random.randint(5,15,100)

array([10,  9, 14,  8, 13, 14,  6,  5, 13, 14,  9,  7, 11,  5,  6,  9, 10,
        8,  8, 14,  7, 14, 11,  7,  9,  5, 12, 13,  9, 13, 14, 10,  8,  8,
        5, 11, 13,  7, 14, 13, 14, 10, 14,  7,  5,  6,  5, 14,  8, 12,  5,
       11, 12, 12, 13, 11,  6,  7,  5, 14, 11,  7,  7,  9,  5, 12, 10, 11,
        6,  5,  6,  8,  8, 14, 12, 11, 14, 10,  9, 14,  6,  6, 14,  7, 14,
        9, 14,  6,  7,  6, 12, 12, 10,  9,  8,  5,  9, 11, 12,  9])

In [84]:
arr=np.arange(25)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [86]:
arr.shape

(25,)

In [87]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
arr_new=arr.reshape(5,5)

In [90]:
arr_new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr_new.shape

(5, 5)

In [92]:
arr5=np.random.randint(0,50,10)

In [93]:
arr5

array([22, 25, 47, 27, 49, 25, 34,  1, 41, 46])

In [94]:
arr5.max()

49

In [95]:
arr5.min()

1

In [96]:
np.max(arr5)

49

In [97]:
np.min(arr5)

1

In [98]:
arr5

array([22, 25, 47, 27, 49, 25, 34,  1, 41, 46])

In [99]:
arr5.argmax()

4

In [100]:
arr5.argmin()

7

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [102]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [103]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [104]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [106]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [108]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [111]:
np.arange(5,20).reshape(5,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [113]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [114]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [1]:
### Indexing Arrays

In [2]:
import numpy as np

In [3]:
arr1=np.arange(5,15)

In [4]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr1[7]

12

In [6]:
arr1[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5])

In [7]:
arr1[4:8]

array([ 9, 10, 11, 12])

In [8]:
## Broadcasting

In [9]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr1[3:7]

array([ 8,  9, 10, 11])

In [11]:
arr2=arr1[3:7]

In [12]:
arr2

array([ 8,  9, 10, 11])

In [13]:
arr2[1:3]

array([ 9, 10])

In [14]:
arr2[1:3]=67

In [15]:
arr2

array([ 8, 67, 67, 11])

In [16]:
arr1

array([ 5,  6,  7,  8, 67, 67, 11, 12, 13, 14])

In [17]:
### Indexing 2D arrays

In [18]:
arr3=np.arange(1,26).reshape(5,5)

In [19]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr3[3,3]

19

In [21]:
arr3[2,4]

15

In [22]:
arr3[1:3,1]

array([ 7, 12])

In [23]:
arr3[2:4,3]

array([14, 19])

In [25]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
arr3[1:3,2]

array([ 8, 13])

In [27]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr3[2:4,4]

array([15, 20])

In [29]:
arr3[2:4,4:5]

array([[15],
       [20]])

In [30]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
arr3[2:3,2:4]

array([[13, 14]])

In [33]:
arr3[2:4,0:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
arr3[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
arr3[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [37]:
arr3[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [38]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
arr3[[1,3],[1,3]]

array([ 7, 19])

In [40]:
arr3[[1,3],[0,4]]

array([ 6, 20])

In [41]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
arr3[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr5=np.arange(1,15)

In [45]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
arr5>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [47]:
arr5[arr5>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
arr5[arr5<=4]

array([1, 2, 3, 4])

In [50]:
### numpy Operations

In [51]:
arr6=np.arange(0,10)

In [52]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr6+arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
arr6-arr6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr6*arr6

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [56]:
arr6**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [57]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr6/arr6

C:\Users\Admin\AppData\Local\Temp/ipykernel_764/61916801.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr6/arr6


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
1/arr6

C:\Users\Admin\AppData\Local\Temp/ipykernel_764/3180675830.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr6


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [60]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
np.sin(arr6)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
np.log(arr6)

C:\Users\Admin\AppData\Local\Temp/ipykernel_764/3307335837.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr6)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [64]:
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
arr3.sum()

325

In [67]:
np.sum(arr3)

325

In [69]:
np.std(arr3)

7.211102550927978

In [70]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
arr3.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [72]:
arr3.sum(axis=0)

array([55, 60, 65, 70, 75])

In [73]:
## fancy Indexing

In [75]:
arr7=np.zeros((10,10))

In [76]:
arr7

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
for v in range(10):
    arr7[v]=v

In [79]:
arr7

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [80]:
arr7[[2,8,4,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [81]:
arr7[[5,1,8,3]]

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [82]:
pwd

'C:\\Users\\Admin'